/**
 * Output generation: Lua file writer and statistics printer.
 */

const {
    LIST_SIZE_FULL_WEIGHT,
    LIST_VOLUME_FULL_WEIGHT,
    RARITY_THRESHOLDS,
    RARITY_ORDER,
    TIER_MIN_OCCURRENCES,
    VERSION_LABEL,
} = require('./config');

const { getRawRarityTier, getAdjustedRarity } = require('./rarity');

/**
 * Generate Lua output file content.
 */
function generateLuaFile(itemData, itemRegistry) {
    const versionTag = VERSION_LABEL !== 'auto' ? ` (${VERSION_LABEL})` : '';
    let lua = `--[[
    Item Rarity Data${versionTag} - Auto-generated by calculate-rarity.js
    
    Method: List-Size-Weighted Real Chance (multi-source)
    Sources: ProceduralDistributions, Distributions, VehicleDistributions
    
    For each item in each list: realChance = weight / listTotalWeight
    Each list's contribution is weighted by two factors:
      sizeWeight  = min(listItems, ${LIST_SIZE_FULL_WEIGHT}) / ${LIST_SIZE_FULL_WEIGHT}
      volumeWeight = min(totalWeight, ${LIST_VOLUME_FULL_WEIGHT}) / ${LIST_VOLUME_FULL_WEIGHT}
      listWeight = sizeWeight × volumeWeight
    Micro-lists (zombie outfits, totalWeight ~0.001) contribute almost nothing.
    Real loot containers (totalWeight 50-500) contribute fully. No data is discarded.
    
    Adjustments:
    - Confidence threshold: Legendary needs 3+ occurrences, Epic needs 2+
    - Category cap: Junk/Hidden/ZedDmg items capped at lower tiers
    - Derived items: Box contents inherit rarity from their container
    - Crafted items: Items not in loot tables but craftable via recipes
    - Cooked/filled: Cooking results and water-filled containers → crafted
    - Forage items: Items from forageDefinitions.lua (with explicit game-defined tiers)
    - Zombie drops: Items from AttachedWeaponDefinitions + ClothingSelectionDefinitions
    - Manual overrides: Hardcoded world spawns (Generator, Chainsaw, Blacksmith books)
    - Default items: All remaining game items → uncommon
    
    Thresholds:
    - Legendary: < ${RARITY_THRESHOLDS.legendary} (3+ occurrences required)
    - Epic: ${RARITY_THRESHOLDS.legendary} - ${RARITY_THRESHOLDS.epic} (2+ occurrences required)
    - Rare: ${RARITY_THRESHOLDS.epic} - ${RARITY_THRESHOLDS.rare}
    - Uncommon: ${RARITY_THRESHOLDS.rare} - ${RARITY_THRESHOLDS.uncommon}
    - Common: > ${RARITY_THRESHOLDS.uncommon}
    - Crafted: items only obtainable via crafting (not found in loot tables)
]]

ItemRarityData = {
`;
    
    const defaultRarityOrder = { rare: 0, uncommon: 1, common: 2 };
    const sortedItems = Object.entries(itemData)
        .sort((a, b) => {
            const aSpecial = a[1].isCrafted ? 5 : a[1].isDefault ? 4 : a[1].isZombieDrop ? 3 : a[1].isForage ? 2 : a[1].isManualOverride ? 1 : 0;
            const bSpecial = b[1].isCrafted ? 5 : b[1].isDefault ? 4 : b[1].isZombieDrop ? 3 : b[1].isForage ? 2 : b[1].isManualOverride ? 1 : 0;
            if (aSpecial !== bSpecial) return aSpecial - bSpecial;
            if (aSpecial === 4 && bSpecial === 4) {
                const aR = defaultRarityOrder[a[1].defaultRarity || 'uncommon'] || 1;
                const bR = defaultRarityOrder[b[1].defaultRarity || 'uncommon'] || 1;
                if (aR !== bR) return aR - bR;
            }
            if (aSpecial > 0) return a[0].localeCompare(b[0]);
            // Loot items: sort by chance, then by name as tiebreaker for deterministic output
            const chanceDiff = a[1].totalRealChance - b[1].totalRealChance;
            if (chanceDiff !== 0) return chanceDiff;
            return a[0].localeCompare(b[0]);
        });
    
    for (const [itemName, data] of sortedItems) {
        if (data.isCrafted) {
            lua += `    ["${itemName}"] = { chance = 0, rarity = "crafted", occurrences = 0 },\n`;
        } else if (data.isDefault) {
            const defRarity = data.defaultRarity || 'uncommon';
            lua += `    ["${itemName}"] = { chance = 0, rarity = "${defRarity}", occurrences = 0 },\n`;
        } else if (data.isManualOverride) {
            lua += `    ["${itemName}"] = { chance = 0, rarity = "${data.manualRarity}", occurrences = 0 },\n`;
        } else if (data.isForage) {
            lua += `    ["${itemName}"] = { chance = 0, rarity = "${data.forageRarity}", occurrences = 0 },\n`;
        } else if (data.isZombieDrop) {
            lua += `    ["${itemName}"] = { chance = 0, rarity = "${data.zombieRarity}", occurrences = 0 },\n`;
        } else {
            const registryItem = itemRegistry ? itemRegistry[itemName] : null;
            const displayCategory = registryItem ? registryItem.displayCategory : null;
            
            const rarity = getAdjustedRarity(
                data.totalRealChance,
                data.occurrences,
                displayCategory
            );
            const chance = data.totalRealChance.toFixed(6);
            
            lua += `    ["${itemName}"] = { chance = ${chance}, rarity = "${rarity}", occurrences = ${data.occurrences} },\n`;
        }
    }
    
    lua += `}

return ItemRarityData
`;
    
    return lua;
}

/**
 * Print statistics about the calculated rarities.
 */
function printStatistics(itemData, itemRegistry) {
    const stats = {
        legendary: 0, epic: 0, rare: 0, uncommon: 0, common: 0, crafted: 0
    };
    
    let demotedCount = 0;
    let cappedCount = 0;
    let derivedCount = 0;
    
    let minChance = Infinity;
    let maxChance = 0;
    let minItem = '';
    let maxItem = '';
    
    let defaultCount = 0;
    let zombieDropCount = 0;
    let forageCount = 0;
    let manualCount = 0;
    
    for (const [itemName, data] of Object.entries(itemData)) {
        if (data.isCrafted) {
            stats.crafted++;
            continue;
        }
        if (data.isDefault) {
            defaultCount++;
            const defRarity = data.defaultRarity || 'uncommon';
            stats[defRarity] = (stats[defRarity] || 0) + 1;
            continue;
        }
        if (data.isManualOverride) {
            manualCount++;
            stats[data.manualRarity] = (stats[data.manualRarity] || 0) + 1;
            continue;
        }
        if (data.isForage) {
            forageCount++;
            stats[data.forageRarity] = (stats[data.forageRarity] || 0) + 1;
            continue;
        }
        if (data.isZombieDrop) {
            zombieDropCount++;
            stats[data.zombieRarity] = (stats[data.zombieRarity] || 0) + 1;
            continue;
        }
        
        const registryItem = itemRegistry ? itemRegistry[itemName] : null;
        const displayCategory = registryItem ? registryItem.displayCategory : null;
        
        const rawRarity = getRawRarityTier(data.totalRealChance);
        const adjustedRarity = getAdjustedRarity(
            data.totalRealChance,
            data.occurrences,
            displayCategory
        );
        
        stats[adjustedRarity]++;
        
        if (rawRarity !== adjustedRarity) {
            const minOcc = TIER_MIN_OCCURRENCES[rawRarity];
            if (minOcc && data.occurrences < minOcc) {
                demotedCount++;
            } else {
                cappedCount++;
            }
        }
        
        if (data.derivedFrom) {
            derivedCount++;
        }
        
        if (data.totalRealChance < minChance) {
            minChance = data.totalRealChance;
            minItem = itemName;
        }
        if (data.totalRealChance > maxChance) {
            maxChance = data.totalRealChance;
            maxItem = itemName;
        }
    }
    
    const totalItems = Object.keys(itemData).length;
    const lootItems = totalItems - stats.crafted - defaultCount - zombieDropCount - forageCount - manualCount;
    
    console.log('\n=== RARITY STATISTICS ===\n');
    console.log(`Total items: ${totalItems} (${lootItems} loot + ${forageCount} forage + ${zombieDropCount} zombie + ${manualCount} manual + ${defaultCount} default + ${stats.crafted} crafted)`);
    console.log('');
    console.log('Loot Distribution:');
    console.log(`  Legendary: ${stats.legendary} items`);
    console.log(`  Epic:      ${stats.epic} items`);
    console.log(`  Rare:      ${stats.rare} items`);
    console.log(`  Uncommon:  ${stats.uncommon} items`);
    console.log(`  Common:    ${stats.common} items`);
    console.log('');
    console.log(`Crafted (no loot): ${stats.crafted} items`);
    console.log('');
    console.log('Adjustments applied:');
    console.log(`  Confidence demotions: ${demotedCount} items (low occurrences)`);
    console.log(`  Category caps:        ${cappedCount} items (Junk/Hidden/etc)`);
    console.log(`  Derived items:        ${derivedCount} items (from containers)`);
    console.log(`  Forage items:         ${forageCount} items (from forageDefinitions.lua)`);
    console.log(`  Zombie drop items:    ${zombieDropCount} items (from outfit/weapon definitions)`);
    console.log(`  Manual overrides:     ${manualCount} items (hardcoded world spawns)`);
    console.log(`  Default (registry):   ${defaultCount} items (not in any source, default uncommon)`);
    console.log('');
    console.log(`Rarest item: ${minItem} (chance: ${minChance.toFixed(6)})`);
    console.log(`Most common: ${maxItem} (chance: ${maxChance.toFixed(6)})`);
    console.log('');
}

module.exports = {
    generateLuaFile,
    printStatistics,
};
